In [ ]:
symbols = "dsadsad"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

print(codes)

symbols = '$¢£¥€¤'
codes = [ord(symbol) for symbol in symbols]
print(codes)

[100, 115, 97, 100, 115, 97, 100]
[36, 162, 163, 165, 8364, 164]


In [ ]:
x = "dsadasd"
dummy = [ord(x) for x in x]
print(x)
print(dummy)

dsadasd
[100, 115, 97, 100, 97, 115, 100]


In [ ]:
symbols = "sadsaafsj"
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
print(beyond_ascii)

beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
print(beyond_ascii)

print(f"map(ord, symbols) = {map(ord, symbols)}")


[]
[]
map(ord, symbols) = <map object at 0x7a5796c81b40>


In [ ]:
colors = ['blacks','white']
sizes = ['S','M','L']
tshirts = [(color,size) for color in colors for size in sizes]
print(tshirts)

for color in colors:
    for size in sizes:
        print((color,size))

[('blacks', 'S'), ('blacks', 'M'), ('blacks', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('blacks', 'S')
('blacks', 'M')
('blacks', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [ ]:
symbols = 'faadfd'
ord_s =tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(102, 97, 97, 100, 102, 100)


In [ ]:
colors = ['black','white']
sizes = ['S','M','L']

for tshirt in ('%s %s' % (c,s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


In [ ]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA','31195855'),('BRA','CE342567'),('ESP','XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [ ]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [ ]:
city, year, pop,chg, area =('Tokyo', 2003, 32450, 0.66, 8014)
print(city)
print(year)
print(pop)
print(chg)
print(area)

Tokyo
2003
32450
0.66
8014


In [ ]:
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
print(city)

Tokyo


In [ ]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)
print(longitude)

33.9425
-118.408056


In [ ]:
a = 10; b=20
b,a = a,b
print(a)
print(b)

20
10


In [ ]:
divmod(20,8)

(2, 4)

In [ ]:
t = (20,8)
divmod(*t)

(2, 4)

In [ ]:
quotient, remainder = divmod(*t)
print(quotient)
print(remainder)

2
4


In [ ]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
print(filename)

idrsa.pub


In [ ]:
a,b, *rest = range(5)
print(a)
print(b)
print(rest)

0
1
[2, 3, 4]


In [ ]:
a, *body, c, d = range(5)
print(a)
print(body)
print(c)
print(d)

0
[1, 2]
3
4


In [ ]:
*head,b,c,d = range(5)
head,b,c,d

([0, 1], 2, 3, 4)

In [ ]:
metro_areas = [
    ("Tokyo","JP",36.933,(35,139)),
    ("Delhi","IN",21,(28,77)),
    ("Mexico City","MX",20,(48,-74)),
    ("NewYork","US",20,(40,-74)),
    ("Sao Paulo","BR",19,(-23,-46))
    ]
print('{:15} | {:^9} | {:^9}'.format('','lat.','long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))
#

                |   lat.    |   long.  
Mexico City     |   48.0000 |  -74.0000
NewYork         |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [ ]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
print(tokyo)

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))


In [ ]:
tokyo.population


36.933

In [ ]:
tokyo[1]

'JP'

In [ ]:
City._fields

('name', 'country', 'population', 'coordinates')

In [ ]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))

In [ ]:
dehli = City._make(delhi_data)
dehli._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613889, long=77.208889)}

In [ ]:
l = [10,20,30,40,50,60]
l[:2]

[10, 20]

In [ ]:
l[:3]

[10, 20, 30]

In [ ]:
l[3:]

[40, 50, 60]

In [ ]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
l = list(range(10))
l[2:5] = [20,30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [ ]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [ ]:
l[3::2] = [11,22]
l

[0, 1, 20, 11, 5, 22, 9]

In [ ]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [ ]:
l = [1,2,3]
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
board = [['_']*3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [ ]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [ ]:
weird_board = [['_']*3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [ ]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [ ]:
row = ['_'] *3
board = []
for i in range(3):
  board.append(row)

board[1][2] = 'X'
board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [ ]:
board = []
for i in range(3):
  row = ['_']*3
  board.append(row)

print(board)
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [ ]:
l = [1,2,3]
id(l)

134516602164736

In [ ]:
l *= 2

In [ ]:
l

[1, 2, 3, 1, 2, 3]

In [ ]:
id(l)

134516602164736

In [ ]:
t = (1,2,3)
id(t)

134516604756224

In [ ]:
t *=2
id(t)

134516603697472

In [ ]:
fruits = ['grape','raspberry','apple','banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [ ]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [ ]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [ ]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [ ]:
sorted(fruits,key=len,reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [ ]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [ ]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [ ]:
from array import array
from random import random

floats = array('d',(random() for i in range(10**7)))
print(floats[-1])

0.47659376527653285


In [ ]:
with open('floats.bin','wb') as f:
  floats.tofile(f)

In [ ]:
floats2 = array('d')
with open('floats.bin','rb') as f:
  floats2.fromfile(f,10**7)

In [ ]:
floats[-1]

0.47659376527653285

In [ ]:
floats == floats2

True

In [ ]:
import array
numbers = array.array('h',[-2,-1,0,1,2])
memv = memoryview(numbers)
len(memv)

5

In [ ]:
memv[0]

-2

In [ ]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [ ]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [ ]:
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.shape

(12,)

In [ ]:
a.shape = 3,4

In [ ]:
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[2]

array([ 8,  9, 10, 11])

In [ ]:
a[2,1]

np.int64(9)

In [ ]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])